services:
  postgres-offline-unlock:
    container_name: postgres_offline_unlock
    image: postgres:16
    command: "postgres -c 'port=5247'"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_PORT: 5247
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5247:5247"
    networks:
      - db
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -p 5247 -U postgres"]
      interval: 2s
      timeout: 2s
      retries: 10
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  db_data:

networks:
  db:
    driver: bridge
