FROM node:21.6.2-alpine

ARG SHOPIFY_API_KEY
ENV SHOPIFY_API_KEY=$SHOPIFY_API_KEY
ARG SHOPIFY_OFFLINE_DISCOUNT_ID
ENV SHOPIFY_OFFLINE_DISCOUNT_ID=$SHOPIFY_OFFLINE_DISCOUNT_ID
ARG OFFLINE_WEB_API_URL
ENV OFFLINE_WEB_API_URL=$OFFLINE_WEB_API_URL
ARG OFFLINE_GATES_HANDLE
ENV OFFLINE_GATES_HANDLE=$OFFLINE_GATES_HANDLE
ARG DATABASE_URL
ENV DATABASE_URL=$DATABASE_URL
ARG SHOPIFY_API_EXTERNAL_SECRET
ENV SHOPIFY_API_EXTERNAL_SECRET=$SHOPIFY_API_EXTERNAL_SECRET

EXPOSE 3000

WORKDIR /app
COPY . .


# Install pnpm
RUN npm install -g pnpm

# Install all dependencies
RUN pnpm install

# Build the application
RUN pnpm run build

# Remove dev dependencies
RUN pnpm prune --prod

ENV NODE_ENV=production

CMD ["pnpm", "run", "docker-start"]
