# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "9eb6e72612f27eaef4ad396f971978b1"
extension_directories = [
  "extensions/offline-discount",
  "extensions/offline-exclusive-staging",
  "extensions/offline-connect"
]
name = "Offline Unlock Staging"
handle = "offline-unlock-staging"
application_url = "https://staging.unlock-shopify.offline.live"
embedded = true

[build]
automatically_update_urls_on_dev = false
dev_store_url = "offline-key.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_discounts,read_gates,write_discounts,write_gates,write_products,read_locales"

[auth]
redirect_urls = [
  "https://staging.unlock-shopify.offline.live/auth/callback",
  "https://staging.unlock-shopify.offline.live/auth/shopify/callback",
  "https://staging.unlock-shopify.offline.live/api/auth/callback"
]

[webhooks]
api_version = "unstable"

[app_proxy]
url = "https://staging.unlock-shopify.offline.live"
subpath = "offline"
prefix = "apps"

[pos]
embedded = false