# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "4882183f4bde802d2e5d230636649df4"
extension_directories = [
  "extensions/offline-discount",
  "extensions/offline-exclusive-development",
  "extensions/offline-gate"
]
name = "Offline Unlock Development"
handle = "offline-unlock-development"
application_url = "https://faq-travels-advertisements-norwegian.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "offline-unlock.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_discounts,read_gates,write_discounts,write_gates,write_products"

[auth]
redirect_urls = [
  "https://faq-travels-advertisements-norwegian.trycloudflare.com/auth/callback",
  "https://faq-travels-advertisements-norwegian.trycloudflare.com/auth/shopify/callback",
  "https://faq-travels-advertisements-norwegian.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "unstable"
