# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "c63bcb7cffdc32d2618c7241c50ca1ff"
extension_directories = [
  "extensions/offline-discount",
  "extensions/offline-exclusive-development",
  "extensions/offline-connect"
]
name = "Offline Unlock Development"
handle = "offline-unlock-development"
application_url = "https://kill-plot-lcd-apnic.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "offline-unlock.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_discounts,read_gates,read_locales,read_themes,write_discounts,write_gates,write_products"

[auth]
redirect_urls = [
  "https://kill-plot-lcd-apnic.trycloudflare.com/auth/callback",
  "https://kill-plot-lcd-apnic.trycloudflare.com/auth/shopify/callback",
  "https://kill-plot-lcd-apnic.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "unstable"

[app_proxy]
url = "https://kill-plot-lcd-apnic.trycloudflare.com"
subpath = "offline"
prefix = "apps"
