api_version = "unstable"

[[extensions]]
handle = "offline-exclusive"
name = "Offline Exclusive"
description = "Offline Exclusive"
type = "function"

  [[extensions.targeting]]
  target = "purchase.validation.run"
  input_query = "../offline-exclusive/src/run.graphql"

  [extensions.build]
  command = "cd ../offline-exclusive && cargo wasi build --release --features prod"
  path = "../offline-exclusive/target/wasm32-wasi/release/offline-exclusive.wasm"
  watch = [ "../offline-exclusive/**", "*.toml" ]

  [extensions.ui.paths]
  create = "/"
  details = "/"
