# Exported from Render on 2024-09-16T15:43:21Z
databases:
  - name: offline-unlock-staging-postgres
    databaseName: offline_unlock_staging_postgres_pday
    user: offline_unlock_staging_postgres_pday_user
    plan: starter
    region: frankfurt
    ipAllowList:
      - source: 0.0.0.0/0
        description: everywhere
    postgresMajorVersion: "16"
services:
  - type: web
    name: shopify-unlock-staging-app
    runtime: docker
    repo: https://github.com/OfflineHQ/shopify-unlock
    plan: free
    envVars:
      - key: SHOPIFY_OFFLINE_DISCOUNT_ID
        sync: false
      - key: SHOPIFY_APP_URL
        sync: false
      - key: SHOPIFY_API_SECRET
        sync: false
      - key: SHOPIFY_API_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: offline-unlock-staging-postgres
          property: connectionString
      - fromGroup: Shopify Unlock Staging
    region: frankfurt
    dockerContext: .
    dockerfilePath: ./Dockerfile
    domains:
      - staging.unlock-shopify-remix.offline.live
      - staging.unlock-shopify.offline.live
    autoDeploy: false
version: "1"
